#!/bin/bash
echo "Please input your comment:"
read comment
hexo clean
hexo g
git add -A
git commit -m "$comment"
git push origin master
cp -R ~/hexo/blog/public/* ~/hexo/wangyubin2015.github.io/
cd ~/hexo/wangyubin2015.github.io/
git add -A
git commit -m "$comment"
git push origin master
